use sdl2::rect::Point;

pub const CASE_SIZE :u32 = 40;

pub const GRID_WIDTH : u32 = 20;

pub const GRID_HEIGHT :u32 = 20;

pub const GRID_WIDTH_PIXELS : u32 = GRID_WIDTH * CASE_SIZE;

pub const GRID_HEIGHT_PIXELS :u32 = GRID_HEIGHT * CASE_SIZE;

pub const CAR_SPEED : u16 = 2;

pub const MAP_CENTER : [(u32,u32);4] = [(GRID_WIDTH/2-1,GRID_HEIGHT/2-1),(GRID_WIDTH/2-1,GRID_HEIGHT/2),(GRID_WIDTH/2,GRID_HEIGHT/2-1),(GRID_WIDTH/2,GRID_HEIGHT/2)];
